<?php
$_product    = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <dl>
    <?php foreach($_attributes as $_attribute): ?>
        <dt><label class="required"><em>*</em><?php echo $_attribute->getLabel() ?></label></dt>
        <dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
            <div class="input-box">
                <select name="super_attribute[<?php echo $this->getGiftUid(); ?>][<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $this->getGiftUid(); ?>-<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select super-attribute-select-<?php echo $this->getGiftUid(); ?>">
                    <option><?php echo $this->__('Choose an Option...') ?></option>
                  </select>
              </div>
        </dd>
    <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        var spConfig_<?php echo $this->getGiftUid(); ?> = new Product.Config(<?php echo $this->getJsonConfig() ?>,'<?php echo $this->getGiftUid(); ?>');
    </script>

<?php endif;?>

