<?php if ($this->getItems()->getSize()): ?>
    <div class="block block-gifts">
        <div class="block-title">
            <strong><span><?php echo mage::helper('giftpromo')->__('Gift Promotions') ?></span></strong>
        </div>
        <div class="block-content">
            <p class="block-subtitle"><?php echo mage::helper('giftpromo')->__(
                    'Gift Promotions to be added to cart when purchased.'
                ) ?></p>
            <ol class="mini-products-list" id="block-gifts">
                <?php foreach ($this->getItems() as $_item): ?>
                    <li class="item">
                        <div class="product">
                            <?php if ($this->canLinkItem($_item)): ?>
                            <a href="<?php echo $_item->getProductUrl() ?>"
                               title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image">
                                <?php endif; ?>
                                <img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(
                                    50
                                ) ?>" width="50" height="50" alt="<?php echo $this->htmlEscape($_item->getName()) ?>"/>
                                <?php if ($this->canLinkItem($_item)): ?>
                            </a>
                        <?php endif; ?>
                            <div class="product-details">
                                <p class="product-name">
                                    <?php if ($this->canLinkItem($_item)): ?>
                                    <a
                                        href="<?php echo $_item->getProductUrl() ?>">
                                        <?php endif; ?>
                                        <?php echo $this->htmlEscape(
                                            $_item->getName()
                                        ) ?>
                                        <?php if ($this->canLinkItem($_item)): ?>
                                    </a>
                                <?php endif; ?>
                                </p>
                                <?php echo $this->getPriceHtml($_item, true, '-gifts') ?>
                                <?php if (!$_item->getIsSalable()): ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__(
                                                'Out of stock'
                                            ) ?></span></p>
                                <?php endif; ?>
                            </div>
                            <?php if ($_item->getGiftedQtyMax() > 0): ?>
                                <p class="max-allowed-gifts">Maximum of <?php echo $_item->getGiftedQtyMax() ?> allowed
                                    in cart.</p>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach ?>
            </ol>
            <script type="text/javascript">decorateList('block-gifts', 'none-recursive')</script>
        </div>
    </div>
<?php endif ?>